### ISSUE TITLE
Handling dates

### ISSUE THREAD

**Issue by coret** [cgeltly/treechecker#10]
One of the errors I see ("The DEAT event of I1076 occurs before the BIRT event.") is based on:

1 BIRT
2 DATE 30 Mar 1592
....
1 DEAT
2 DATE 1592

It seems 1592 (which is valid in the GEDCOM specification) is rewritten to 0-0-1592 which is then determined to be before 30-03-1592. The "0-0" part is not ok here. The person died on a undetermined day in the year 1592, that's what "2 DATE 1592" means. So issueing an error here seems incorrect.

**Comment by cgeltly** [comment]
This is a parse issue. I'm getting a parse error with 0-0-1592 in a DEAT event, yet these date formats have presumably been parsed before.
